export { handleHTML } from './handleHTML'
export { contentAfterReplaced } from './contentAfterReplaced'
export { getOEmbed } from './getOembed'
export { getDataTheme } from './getDataTheme'
export { getLang } from './getLang'
export { getOembedProvidersUrl } from './getOembedProvidersUrls'
export { isUrl } from './isUrl'
export { getPosts } from './getPosts'
export { setDataTheme } from './setDataTheme'
export { setDefaultThemeAsDark } from './setDefaultThemeAsDark'
export { makeReactTweet } from './makeReactTweet'

