import '@/app/globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import ThemeSetter from '@/components/ThemeSetter'
import 'devicon/devicon.min.css'


// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default ({ children }: { children: React.ReactNode }) => {
  return (
    <html
      lang='ja'
      data-theme='night'
    >
      <body className=''>
        <ThemeSetter>
          {children}
        </ThemeSetter>
      </body>
    </html>
  )
}
