import "@/app/globals.css";
import "@code-hike/mdx/dist/index.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@main/_components/server/Navbar";
import { Providers } from "@main/_components/client/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="dark">
      <body>
        <Providers>
          <Navbar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
