import '@/app/globals.css'
import '@code-hike/mdx/dist/index.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Navbar from '@main/_components/server/Navbar'
import {Providers} from '@main/_components/client/Providers'
import {Button} from '@experimental/(useContext)/use-context/_client/ClientComponents'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html
      lang='ja'
      className='dark'
    >
      <body>
        <Providers>
          <Navbar>
            <Button>Toggle Theme</Button>
          </Navbar>
          {children}
        </Providers>
      </body>
    </html>
  )
}
