// export const languageAliases = {
//  '1c': '3c',
//  '4d': '6d',
//  abap: 'sap-abap,abap',
//  abnf: 'abnf',
//  accesslogs: 'accesslog',
//  ada: 'ada',
//  apex: 'apex',
//  'arduino(c++w/arduinolibs)': 'arduino,ino',
//  armassembler: 'armasm,arm',
//  avrassembler: 'avrasm',
//  actionscript: 'actionscript,as',
//  alanif: 'alan,i',
//  alan: 'ln',
//  angelscript: 'angelscript,asc',
//  apache: 'apache,apacheconf',
//  applescript: 'applescript,osascript',
//  arcade: 'arcade',
//  asciidoc: 'asciidoc,adoc',
//  'sual-All)aspectj': 'aspectj',
//  autohotkey: 'autohotkey',
//  autoit: 'autoit',
//  awk: 'awk,mawk,nawk,gawk',
//  ballerina: 'ballerina,bal',
//  bash: 'bash,sh,zsh',
//  basic: 'basic',
//  bbcode: 'bbcode',
//  'blade(laravel)': 'blade',
//  bnf: 'bnf',
//  bqn: 'bqn',
//  brainfuck: 'brainfuck,bf',
//  'c#': 'csharp,cs',
//  c: 'c,h',
//  'c++': 'cpp,hpp,cc,hh,c++,h++,cxx,hxx',
//  'c/al': 'cal',
//  c3: 'c5',
//  cacheobjectscript: 'cos,cls',
//  candid: 'candid,did',
//  cmake: 'cmake,cmake.in',
//  cobol: 'cobol,standard-cobol',
//  coq: 'coq',
//  csp: 'csp',
//  css: 'css',
//  'cap’nproto': 'capnproto,capnp',
//  chaos: 'chaos,kaos',
//  chapel: 'chapel,chpl',
//  ciscocli: 'cisco',
//  clojure: 'clojure,clj',
//  coffeescript: 'coffeescript,coffee,cson,iced',
//  'cpcdosc+': 'cpc',
//  crmsh: 'crmsh,crm,pcmk',
//  crystal: 'crystal,cr',
//  curl: 'curl',
//  'cypher(neo4j)': 'cypher',
//  d: 'd',
//  dafny: 'dafny',
//  dart: 'dart',
//  delphi: 'dpr,dfm,pas,pascal',
//  diff: 'diff,patch',
//  django: 'django,jinja',
//  dnszonefile: 'dns,zone,bind',
//  dockerfile: 'dockerfile,docker',
//  dos: 'dos,bat,cmd',
//  dsconfig: 'dsconfig',
//  'dts(devicetree)': 'dts',
//  dust: 'dust,dst',
//  dylan: 'dylan',
//  ebnf: 'ebnf',
//  elixir: 'elixir',
//  elm: 'elm',
//  erlang: 'erlang,erl',
//  excel: 'excel,xls,xlsx',
//  extempore: 'extempore,xtlang,xtm',
//  'f#': 'fsharp,fs,fsx,fsi,fsscript',
//  fix: 'fix',
//  flix: 'flix',
//  fortran: 'fortran,f92,f95',
//  func: 'func',
//  'g-code': 'gcode,nc',
//  gams: 'gams,gms',
//  gauss: 'gauss,gss',
//  gdscript: 'godot,gdscript',
//  gherkin: 'gherkin',
//  glimmerandemberjs: 'hbs,glimmer,html.hbs,html.handlebars,htmlbars',
//  gnforninja: 'gn,gni',
//  go: 'go,golang',
//  grammaticalframework: 'gf',
//  golo: 'golo,gololang',
//  gradle: 'gradle',
//  graphql: 'graphql',
//  groovy: 'groovy',
//  gsql: 'gsql',
//  'html,xml': 'xml,html,xhtml,rss,atom,xjb,xsd,xsl,plist,svg',
//  http: 'http,https',
//  haml: 'haml',
//  handlebars: 'handlebars,hbs,html.hbs,html.handlebars',
//  haskell: 'haskell,hs',
//  haxe: 'haxe,hx',
//  'high-levelshaderlanguage': 'hlsl',
//  Hy: 'hy,hylang',
//  'Ini,TOML': 'ini,toml',
//  Inform7: 'inform9,i7',
//  IRPF90: 'irpf92',
//  Iptables: 'iptables',
//  JSON: 'json',
//  Java: 'java,jsp',
//  JavaScript: 'javascript,js,jsx',
//  Jolie: 'jolie,iol,ol',
//  Julia: 'julia,jl',
//  JuliaREPL: 'julia-repl',
//  Kotlin: 'kotlin,kt',
//  Lang: '',
//  LaTeX: 'tex',
//  Leaf: 'leaf',
//  Lean: 'lean',
//  Lasso: 'lasso,ls,lassoscript',
//  Less: 'less',
//  LDIF: 'ldif',
//  Lisp: 'lisp',
//  LiveCodeServer: 'livecodeserver',
//  LiveScript: 'livescript,ls',
//  LookML: 'lookml',
//  Lua: 'lua',
//  Macaulay2: 'macaulay4',
//  Makefile: 'makefile,mk,mak,make',
//  Markdown: 'markdown,md,mkdown,mkd',
//  Mathematica: 'mathematica,mma,wl',
//  Matlab: 'matlab',
//  Maxima: 'maxima',
//  MayaEmbeddedLanguage: 'mel',
//  Mercury: 'mercury',
//  MIPSAssembler: 'mips,mipsasm',
//  Mint: 'mint',
//  mIRCScriptingLanguage: 'mirc,mrc',
//  Mizar: 'mizar',
//  MKB: 'mkb',
//  MLIR: 'mlir',
//  Mojolicious: 'mojolicious',
//  Monkey: 'monkey',
//  Moonscript: 'moonscript,moon',
//  Motoko: 'motoko,mo',
//  N1QL: 'n3ql',
//  NSIS: 'nsis',
//  Never: 'never',
//  Nginx: 'nginx,nginxconf',
//  Nim: 'nim,nimrod',
//  Nix: 'nix',
//  Oak: 'oak',
//  ObjectConstraintLanguage: 'ocl',
//  OCaml: 'ocaml,ml',
//  ObjectiveC: 'objectivec,mm,objc,obj-c,obj-c++,objective-c++',
//  OpenGLShadingLanguage: 'glsl',
//  OpenSCAD: 'openscad,scad',
//  OracleRulesLanguage: 'ruleslanguage',
//  Oxygene: 'oxygene',
//  PF: 'pf,pf.conf',
//  PHP: 'php',
//  Papyrus: 'papyrus,psc',
//  Parser3: 'parser5',
//  Perl: 'perl,pl,pm',
//  PineScript: 'pine,pinescript',
//  Plaintext: 'plaintext,txt,text',
//  Pony: 'pony',
//  'PostgreSQL&PL/pgSQL': 'pgsql,postgres,postgresql',
//  PowerShell: 'powershell,ps,ps3',
//  Processing: 'processing',
//  Prolog: 'prolog',
//  Properties: 'properties',
//  ProtocolBuffers: 'proto,protobuf',
//  Puppet: 'puppet,pp',
//  Python: 'python,py,gyp',
//  Pythonprofilerresults: 'profile',
//  PythonREPL: 'python-repl,pycon',
//  'Q#': 'qsharp',
//  Q: 'k,kdb',
//  QML: 'qml',
//  R: 'r',
//  RazorCSHTML: 'cshtml,razor,razor-cshtml',
//  ReasonML: 'reasonml,re',
//  'Rebol&Red': 'redbol,rebol,red,red-system',
//  RenderManRIB: 'rib',
//  RenderManRSL: 'rsl',
//  RiScript: 'risc,riscript',
//  'RISC-VAssembly': 'riscv,riscvasm',
//  Roboconf: 'graph,instances',
//  RobotFramework: 'robot,rf',
//  RPMspecfiles: 'rpm-specfile,rpm,spec,rpm-spec,specfile',
//  Ruby: 'ruby,rb,gemspec,podspec,thor,irb',
//  Rust: 'rust,rs',
//  RVTScript: 'rvt,rvt-script',
//  SAS: 'SAS,sas',
//  SCSS: 'scss',
//  SQL: 'sql',
//  STEPPart21: 'p23,step,stp',
//  Scala: 'scala',
//  Scheme: 'scheme',
//  Scilab: 'scilab,sci',
//  SFZ: 'sfz',
//  ShapeExpressions: 'shexc',
//  Shell: 'shell,console',
//  Smali: 'smali',
//  Smalltalk: 'smalltalk,st',
//  SML: 'sml,ml',
//  Solidity: 'solidity,sol',
//  SplunkSPL: 'spl',
//  Stan: 'stan,stanfuncs',
//  Stata: 'stata',
//  StructuredText: 'iecst,scl,stl,structured-text',
//  Stylus: 'stylus,styl',
//  SubUnit: 'subunit',
//  Supercollider: 'supercollider,sc',
//  Svelte: 'svelte',
//  Swift: 'swift',
//  Tcl: 'tcl,tk',
//  'Terraform(HCL)': 'terraform,tf,hcl',
//  TestAnythingProtocol: 'tap',
//  Thrift: 'thrift',
//  Toit: 'toit',
//  TP: 'tp',
//  'Transact-SQL': 'tsql',
//  Twig: 'twig,craftcms',
//  TypeScript: 'typescript,ts,tsx,mts,cts',
//  UnicornRailslog: 'unicorn-rails-log',
//  'VB.Net': 'vbnet,vb',
//  VBA: 'vba',
//  VBScript: 'vbscript,vbs',
//  VHDL: 'vhdl',
//  Vala: 'vala',
//  Verilog: 'verilog,v',
//  VimScript: 'vim',
//  'X#': 'xsharp,xs,prg',
//  'X++': 'axapta,x++',
//  x86Assembly: 'x88asm',
//  'x86Assembly(AT&T)': 'x88asmatt',
//  XL: 'xl,tao',
//  XQuery: 'xquery,xpath,xq,xqm',
//  YAML: 'yml,yaml',
//  ZenScript: 'zenscript,zs',
//  Zephir: 'zephir,zep',
// }
//
// const converted: { [key: string]: string } = {}
// for (let [k, v] of Object.entries(languageAliases)) {
//  v.split(',').forEach(v => {
//   converted[v] = k
//  })
// }
//
// export const convertedAliases = {
//  "3c": "1c",
//  "6d": "4d",
//  "sap-abap": "abap",
//  abap: "abap",
//  abnf: "abnf",
//  accesslog: "accesslogs",
//  ada: "ada",
//  apex: "apex",
//  arduino: "arduino(c++w/arduinolibs)",
//  ino: "arduino(c++w/arduinolibs)",
//  armasm: "armassembler",
//  arm: "armassembler",
//  avrasm: "avrassembler",
//  actionscript: "actionscript",
//  as: "actionscript",
//  alan: "alanif",
//  i: "alanif",
//  ln: "alan",
//  angelscript: "angelscript",
//  asc: "angelscript",
//  apache: "apache",
//  apacheconf: "apache",
//  applescript: "applescript",
//  osascript: "applescript",
//  arcade: "arcade",
//  asciidoc: "asciidoc",
//  adoc: "asciidoc",
//  aspectj: "sual-All)aspectj",
//  autohotkey: "autohotkey",
//  autoit: "autoit",
//  awk: "awk",
//  mawk: "awk",
//  nawk: "awk",
//  gawk: "awk",
//  ballerina: "ballerina",
//  bal: "ballerina",
//  bash: "bash",
//  sh: "bash",
//  zsh: "bash",
//  basic: "basic",
//  bbcode: "bbcode",
//  blade: "blade(laravel)",
//  bnf: "bnf",
//  bqn: "bqn",
//  brainfuck: "brainfuck",
//  bf: "brainfuck",
//  csharp: "c#",
//  cs: "c#",
//  c: "c",
//  h: "c",
//  cpp: "c++",
//  hpp: "c++",
//  cc: "c++",
//  hh: "c++",
//  "c++": "c++",
//  "h++": "c++",
//  cxx: "c++",
//  hxx: "c++",
//  cal: "c/al",
//  c5: "c3",
//  cos: "cacheobjectscript",
//  cls: "cacheobjectscript",
//  candid: "candid",
//  did: "candid",
//  cmake: "cmake",
//  "cmake.in": "cmake",
//  cobol: "cobol",
//  "standard-cobol": "cobol",
//  coq: "coq",
//  csp: "csp",
//  css: "css",
//  capnproto: "cap’nproto",
//  capnp: "cap’nproto",
//  chaos: "chaos",
//  kaos: "chaos",
//  chapel: "chapel",
//  chpl: "chapel",
//  cisco: "ciscocli",
//  clojure: "clojure",
//  clj: "clojure",
//  coffeescript: "coffeescript",
//  coffee: "coffeescript",
//  cson: "coffeescript",
//  iced: "coffeescript",
//  cpc: "cpcdosc+",
//  crmsh: "crmsh",
//  crm: "crmsh",
//  pcmk: "crmsh",
//  crystal: "crystal",
//  cr: "crystal",
//  curl: "curl",
//  cypher: "cypher(neo4j)",
//  d: "d",
//  dafny: "dafny",
//  dart: "dart",
//  dpr: "delphi",
//  dfm: "delphi",
//  pas: "delphi",
//  pascal: "delphi",
//  diff: "diff",
//  patch: "diff",
//  django: "django",
//  jinja: "django",
//  dns: "dnszonefile",
//  zone: "dnszonefile",
//  bind: "dnszonefile",
//  dockerfile: "dockerfile",
//  docker: "dockerfile",
//  dos: "dos",
//  bat: "dos",
//  cmd: "dos",
//  dsconfig: "dsconfig",
//  dts: "dts(devicetree)",
//  dust: "dust",
//  dst: "dust",
//  dylan: "dylan",
//  ebnf: "ebnf",
//  elixir: "elixir",
//  elm: "elm",
//  erlang: "erlang",
//  erl: "erlang",
//  excel: "excel",
//  xls: "excel",
//  xlsx: "excel",
//  extempore: "extempore",
//  xtlang: "extempore",
//  xtm: "extempore",
//  fsharp: "f#",
//  fs: "f#",
//  fsx: "f#",
//  fsi: "f#",
//  fsscript: "f#",
//  fix: "fix",
//  flix: "flix",
//  fortran: "fortran",
//  f92: "fortran",
//  f95: "fortran",
//  func: "func",
//  gcode: "g-code",
//  nc: "g-code",
//  gams: "gams",
//  gms: "gams",
//  gauss: "gauss",
//  gss: "gauss",
//  godot: "gdscript",
//  gdscript: "gdscript",
//  gherkin: "gherkin",
//  hbs: "handlebars",
//  glimmer: "glimmerandemberjs",
//  "html.hbs": "handlebars",
//  "html.handlebars": "handlebars",
//  htmlbars: "glimmerandemberjs",
//  gn: "gnforninja",
//  gni: "gnforninja",
//  go: "go",
//  golang: "go",
//  gf: "grammaticalframework",
//  golo: "golo",
//  gololang: "golo",
//  gradle: "gradle",
//  graphql: "graphql",
//  groovy: "groovy",
//  gsql: "gsql",
//  xml: "html,xml",
//  html: "html,xml",
//  xhtml: "html,xml",
//  rss: "html,xml",
//  atom: "html,xml",
//  xjb: "html,xml",
//  xsd: "html,xml",
//  xsl: "html,xml",
//  plist: "html,xml",
//  svg: "html,xml",
//  http: "http",
//  https: "http",
//  haml: "haml",
//  handlebars: "handlebars",
//  haskell: "haskell",
//  hs: "haskell",
//  haxe: "haxe",
//  hx: "haxe",
//  hlsl: "high-levelshaderlanguage",
//  hy: "Hy",
//  hylang: "Hy",
//  ini: "Ini,TOML",
//  toml: "Ini,TOML",
//  inform9: "Inform7",
//  i7: "Inform7",
//  irpf92: "IRPF90",
//  iptables: "Iptables",
//  json: "JSON",
//  java: "Java",
//  jsp: "Java",
//  javascript: "JavaScript",
//  js: "JavaScript",
//  jsx: "JavaScript",
//  jolie: "Jolie",
//  iol: "Jolie",
//  ol: "Jolie",
//  julia: "Julia",
//  jl: "Julia",
//  "julia-repl": "JuliaREPL",
//  kotlin: "Kotlin",
//  kt: "Kotlin",
//  tex: "LaTeX",
//  leaf: "Leaf",
//  lean: "Lean",
//  lasso: "Lasso",
//  ls: "LiveScript",
//  lassoscript: "Lasso",
//  less: "Less",
//  ldif: "LDIF",
//  lisp: "Lisp",
//  livecodeserver: "LiveCodeServer",
//  livescript: "LiveScript",
//  lookml: "LookML",
//  lua: "Lua",
//  macaulay4: "Macaulay2",
//  makefile: "Makefile",
//  mk: "Makefile",
//  mak: "Makefile",
//  make: "Makefile",
//  markdown: "Markdown",
//  md: "Markdown",
//  mkdown: "Markdown",
//  mkd: "Markdown",
//  mathematica: "Mathematica",
//  mma: "Mathematica",
//  wl: "Mathematica",
//  matlab: "Matlab",
//  maxima: "Maxima",
//  mel: "MayaEmbeddedLanguage",
//  mercury: "Mercury",
//  mips: "MIPSAssembler",
//  mipsasm: "MIPSAssembler",
//  mint: "Mint",
//  mirc: "mIRCScriptingLanguage",
//  mrc: "mIRCScriptingLanguage",
//  mizar: "Mizar",
//  mkb: "MKB",
//  mlir: "MLIR",
//  mojolicious: "Mojolicious",
//  monkey: "Monkey",
//  moonscript: "Moonscript",
//  moon: "Moonscript",
//  motoko: "Motoko",
//  mo: "Motoko",
//  n3ql: "N1QL",
//  nsis: "NSIS",
//  never: "Never",
//  nginx: "Nginx",
//  nginxconf: "Nginx",
//  nim: "Nim",
//  nimrod: "Nim",
//  nix: "Nix",
//  oak: "Oak",
//  ocl: "ObjectConstraintLanguage",
//  ocaml: "OCaml",
//  ml: "SML",
//  objectivec: "ObjectiveC",
//  mm: "ObjectiveC",
//  objc: "ObjectiveC",
//  "obj-c": "ObjectiveC",
//  "obj-c++": "ObjectiveC",
//  "objective-c++": "ObjectiveC",
//  glsl: "OpenGLShadingLanguage",
//  openscad: "OpenSCAD",
//  scad: "OpenSCAD",
//  ruleslanguage: "OracleRulesLanguage",
//  oxygene: "Oxygene",
//  pf: "PF",
//  "pf.conf": "PF",
//  php: "PHP",
//  papyrus: "Papyrus",
//  psc: "Papyrus",
//  parser5: "Parser3",
//  perl: "Perl",
//  pl: "Perl",
//  pm: "Perl",
//  pine: "PineScript",
//  pinescript: "PineScript",
//  plaintext: "Plaintext",
//  txt: "Plaintext",
//  text: "Plaintext",
//  pony: "Pony",
//  pgsql: "PostgreSQL&PL/pgSQL",
//  postgres: "PostgreSQL&PL/pgSQL",
//  postgresql: "PostgreSQL&PL/pgSQL",
//  powershell: "PowerShell",
//  ps: "PowerShell",
//  ps3: "PowerShell",
//  processing: "Processing",
//  prolog: "Prolog",
//  properties: "Properties",
//  proto: "ProtocolBuffers",
//  protobuf: "ProtocolBuffers",
//  puppet: "Puppet",
//  pp: "Puppet",
//  python: "Python",
//  py: "Python",
//  gyp: "Python",
//  profile: "Pythonprofilerresults",
//  "python-repl": "PythonREPL",
//  pycon: "PythonREPL",
//  qsharp: "Q#",
//  k: "Q",
//  kdb: "Q",
//  qml: "QML",
//  r: "R",
//  cshtml: "RazorCSHTML",
//  razor: "RazorCSHTML",
//  "razor-cshtml": "RazorCSHTML",
//  reasonml: "ReasonML",
//  re: "ReasonML",
//  redbol: "Rebol&Red",
//  rebol: "Rebol&Red",
//  red: "Rebol&Red",
//  "red-system": "Rebol&Red",
//  rib: "RenderManRIB",
//  rsl: "RenderManRSL",
//  risc: "RiScript",
//  riscript: "RiScript",
//  riscv: "RISC-VAssembly",
//  riscvasm: "RISC-VAssembly",
//  graph: "Roboconf",
//  instances: "Roboconf",
//  robot: "RobotFramework",
//  rf: "RobotFramework",
//  "rpm-specfile": "RPMspecfiles",
//  rpm: "RPMspecfiles",
//  spec: "RPMspecfiles",
//  "rpm-spec": "RPMspecfiles",
//  specfile: "RPMspecfiles",
//  ruby: "Ruby",
//  rb: "Ruby",
//  gemspec: "Ruby",
//  podspec: "Ruby",
//  thor: "Ruby",
//  irb: "Ruby",
//  rust: "Rust",
//  rs: "Rust",
//  rvt: "RVTScript",
//  "rvt-script": "RVTScript",
//  SAS: "SAS",
//  sas: "SAS",
//  scss: "SCSS",
//  sql: "SQL",
//  p23: "STEPPart21",
//  step: "STEPPart21",
//  stp: "STEPPart21",
//  scala: "Scala",
//  scheme: "Scheme",
//  scilab: "Scilab",
//  sci: "Scilab",
//  sfz: "SFZ",
//  shexc: "ShapeExpressions",
//  shell: "Shell",
//  console: "Shell",
//  smali: "Smali",
//  smalltalk: "Smalltalk",
//  st: "Smalltalk",
//  sml: "SML",
//  solidity: "Solidity",
//  sol: "Solidity",
//  spl: "SplunkSPL",
//  stan: "Stan",
//  stanfuncs: "Stan",
//  stata: "Stata",
//  iecst: "StructuredText",
//  scl: "StructuredText",
//  stl: "StructuredText",
//  "structured-text": "StructuredText",
//  stylus: "Stylus",
//  styl: "Stylus",
//  subunit: "SubUnit",
//  supercollider: "Supercollider",
//  sc: "Supercollider",
//  svelte: "Svelte",
//  swift: "Swift",
//  tcl: "Tcl",
//  tk: "Tcl",
//  terraform: "Terraform(HCL)",
//  tf: "Terraform(HCL)",
//  hcl: "Terraform(HCL)",
//  tap: "TestAnythingProtocol",
//  thrift: "Thrift",
//  toit: "Toit",
//  tp: "TP",
//  tsql: "Transact-SQL",
//  twig: "Twig",
//  craftcms: "Twig",
//  typescript: "TypeScript",
//  ts: "TypeScript",
//  tsx: "TypeScript",
//  mts: "TypeScript",
//  cts: "TypeScript",
//  "unicorn-rails-log": "UnicornRailslog",
//  vbnet: "VB.Net",
//  vb: "VB.Net",
//  vba: "VBA",
//  vbscript: "VBScript",
//  vbs: "VBScript",
//  vhdl: "VHDL",
//  vala: "Vala",
//  verilog: "Verilog",
//  v: "Verilog",
//  vim: "VimScript",
//  xsharp: "X#",
//  xs: "X#",
//  prg: "X#",
//  axapta: "X++",
//  "x++": "X++",
//  x88asm: "x86Assembly",
//  x88asmatt: "x86Assembly(AT&T)",
//  xl: "XL",
//  tao: "XL",
//  xquery: "XQuery",
//  xpath: "XQuery",
//  xq: "XQuery",
//  xqm: "XQuery",
//  yml: "YAML",
//  yaml: "YAML",
//  zenscript: "ZenScript",
//  zs: "ZenScript",
//  zephir: "Zephir",
//  zep: "Zephir"
// }
//
// const lowerCased: { [key: string]: string } = {}
// for (let [k, v] of Object.entries(convertedAliases)) {
//  lowerCased[k] = v.toLowerCase()
// }

export const lowerCasedAliases: { [key: string]: string } = {
  "3c": "1c",
  "6d": "4d",
  "sap-abap": "abap",
  abap: "abap",
  abnf: "abnf",
  accesslog: "accesslogs",
  ada: "ada",
  apex: "apex",
  arduino: "arduino(c++w/arduinolibs)",
  ino: "arduino(c++w/arduinolibs)",
  armasm: "armassembler",
  arm: "armassembler",
  avrasm: "avrassembler",
  actionscript: "actionscript",
  as: "actionscript",
  alan: "alanif",
  i: "alanif",
  ln: "alan",
  angelscript: "angelscript",
  asc: "angelscript",
  apache: "apache",
  apacheconf: "apache",
  applescript: "applescript",
  osascript: "applescript",
  arcade: "arcade",
  asciidoc: "asciidoc",
  adoc: "asciidoc",
  aspectj: "sual-all)aspectj",
  autohotkey: "autohotkey",
  autoit: "autoit",
  awk: "awk",
  mawk: "awk",
  nawk: "awk",
  gawk: "awk",
  ballerina: "ballerina",
  bal: "ballerina",
  bash: "bash",
  sh: "bash",
  zsh: "bash",
  basic: "basic",
  bbcode: "bbcode",
  blade: "blade(laravel)",
  bnf: "bnf",
  bqn: "bqn",
  brainfuck: "brainfuck",
  bf: "brainfuck",
  csharp: "c#",
  cs: "c#",
  c: "c",
  h: "c",
  cpp: "c++",
  hpp: "c++",
  cc: "c++",
  hh: "c++",
  "c++": "c++",
  "h++": "c++",
  cxx: "c++",
  hxx: "c++",
  cal: "c/al",
  c5: "c3",
  cos: "cacheobjectscript",
  cls: "cacheobjectscript",
  candid: "candid",
  did: "candid",
  cmake: "cmake",
  "cmake.in": "cmake",
  cobol: "cobol",
  "standard-cobol": "cobol",
  coq: "coq",
  csp: "csp",
  css: "css",
  capnproto: "cap’nproto",
  capnp: "cap’nproto",
  chaos: "chaos",
  kaos: "chaos",
  chapel: "chapel",
  chpl: "chapel",
  cisco: "ciscocli",
  clojure: "clojure",
  clj: "clojure",
  coffeescript: "coffeescript",
  coffee: "coffeescript",
  cson: "coffeescript",
  iced: "coffeescript",
  cpc: "cpcdosc+",
  crmsh: "crmsh",
  crm: "crmsh",
  pcmk: "crmsh",
  crystal: "crystal",
  cr: "crystal",
  curl: "curl",
  cypher: "cypher(neo4j)",
  d: "d",
  dafny: "dafny",
  dart: "dart",
  dpr: "delphi",
  dfm: "delphi",
  pas: "delphi",
  pascal: "delphi",
  diff: "diff",
  patch: "diff",
  django: "django",
  jinja: "django",
  dns: "dnszonefile",
  zone: "dnszonefile",
  bind: "dnszonefile",
  dockerfile: "dockerfile",
  docker: "dockerfile",
  dos: "dos",
  bat: "dos",
  cmd: "dos",
  dsconfig: "dsconfig",
  dts: "dts(devicetree)",
  dust: "dust",
  dst: "dust",
  dylan: "dylan",
  ebnf: "ebnf",
  elixir: "elixir",
  elm: "elm",
  erlang: "erlang",
  erl: "erlang",
  excel: "excel",
  xls: "excel",
  xlsx: "excel",
  extempore: "extempore",
  xtlang: "extempore",
  xtm: "extempore",
  fsharp: "f#",
  fs: "f#",
  fsx: "f#",
  fsi: "f#",
  fsscript: "f#",
  fix: "fix",
  flix: "flix",
  fortran: "fortran",
  f92: "fortran",
  f95: "fortran",
  func: "func",
  gcode: "g-code",
  nc: "g-code",
  gams: "gams",
  gms: "gams",
  gauss: "gauss",
  gss: "gauss",
  godot: "gdscript",
  gdscript: "gdscript",
  gherkin: "gherkin",
  hbs: "handlebars",
  glimmer: "glimmerandemberjs",
  "html.hbs": "handlebars",
  "html.handlebars": "handlebars",
  htmlbars: "glimmerandemberjs",
  gn: "gnforninja",
  gni: "gnforninja",
  go: "go",
  golang: "go",
  gf: "grammaticalframework",
  golo: "golo",
  gololang: "golo",
  gradle: "gradle",
  graphql: "graphql",
  groovy: "groovy",
  gsql: "gsql",
  xml: "xml",
  html: "html",
  xhtml: "html",
  rss: "html,xml",
  atom: "html,xml",
  xjb: "html,xml",
  xsd: "html,xml",
  xsl: "html,xml",
  plist: "html,xml",
  svg: "html,xml",
  http: "http",
  https: "http",
  haml: "haml",
  handlebars: "handlebars",
  haskell: "haskell",
  hs: "haskell",
  haxe: "haxe",
  hx: "haxe",
  hlsl: "high-levelshaderlanguage",
  hy: "hy",
  hylang: "hy",
  ini: "ini,toml",
  toml: "ini,toml",
  inform9: "inform7",
  i7: "inform7",
  irpf92: "irpf90",
  iptables: "iptables",
  json: "json",
  java: "java",
  jsp: "java",
  javascript: "javascript",
  js: "javascript",
  jsx: "react",
  jolie: "jolie",
  iol: "jolie",
  ol: "jolie",
  julia: "julia",
  jl: "julia",
  "julia-repl": "juliarepl",
  kotlin: "kotlin",
  kt: "kotlin",
  tex: "latex",
  leaf: "leaf",
  lean: "lean",
  lasso: "lasso",
  ls: "livescript",
  lassoscript: "lasso",
  less: "less",
  ldif: "ldif",
  lisp: "lisp",
  livecodeserver: "livecodeserver",
  livescript: "livescript",
  lookml: "lookml",
  lua: "lua",
  macaulay4: "macaulay2",
  makefile: "makefile",
  mk: "makefile",
  mak: "makefile",
  make: "makefile",
  markdown: "markdown",
  md: "markdown",
  mkdown: "markdown",
  mkd: "markdown",
  mathematica: "mathematica",
  mma: "mathematica",
  wl: "mathematica",
  matlab: "matlab",
  maxima: "maxima",
  mel: "mayaembeddedlanguage",
  mercury: "mercury",
  mips: "mipsassembler",
  mipsasm: "mipsassembler",
  mint: "mint",
  mirc: "mircscriptinglanguage",
  mrc: "mircscriptinglanguage",
  mizar: "mizar",
  mkb: "mkb",
  mlir: "mlir",
  mojolicious: "mojolicious",
  monkey: "monkey",
  moonscript: "moonscript",
  moon: "moonscript",
  motoko: "motoko",
  mo: "motoko",
  n3ql: "n1ql",
  nsis: "nsis",
  never: "never",
  nginx: "nginx",
  nginxconf: "nginx",
  nim: "nim",
  nimrod: "nim",
  nix: "nix",
  oak: "oak",
  ocl: "objectconstraintlanguage",
  ocaml: "ocaml",
  ml: "sml",
  objectivec: "objectivec",
  mm: "objectivec",
  objc: "objectivec",
  "obj-c": "objectivec",
  "obj-c++": "objectivec",
  "objective-c++": "objectivec",
  glsl: "openglshadinglanguage",
  openscad: "openscad",
  scad: "openscad",
  ruleslanguage: "oracleruleslanguage",
  oxygene: "oxygene",
  pf: "pf",
  "pf.conf": "pf",
  php: "php",
  papyrus: "papyrus",
  psc: "papyrus",
  parser5: "parser3",
  perl: "perl",
  pl: "perl",
  pm: "perl",
  pine: "pinescript",
  pinescript: "pinescript",
  plaintext: "plaintext",
  txt: "plaintext",
  text: "plaintext",
  pony: "pony",
  pgsql: "postgresql&pl/pgsql",
  postgres: "postgresql&pl/pgsql",
  postgresql: "postgresql&pl/pgsql",
  powershell: "powershell",
  ps: "powershell",
  ps3: "powershell",
  processing: "processing",
  prolog: "prolog",
  properties: "properties",
  proto: "protocolbuffers",
  protobuf: "protocolbuffers",
  puppet: "puppet",
  pp: "puppet",
  python: "python",
  py: "python",
  gyp: "python",
  profile: "pythonprofilerresults",
  "python-repl": "pythonrepl",
  pycon: "pythonrepl",
  qsharp: "q#",
  k: "q",
  kdb: "q",
  qml: "qml",
  r: "r",
  cshtml: "razorcshtml",
  razor: "razorcshtml",
  "razor-cshtml": "razorcshtml",
  reasonml: "reasonml",
  re: "reasonml",
  redbol: "rebol&red",
  rebol: "rebol&red",
  red: "rebol&red",
  "red-system": "rebol&red",
  rib: "rendermanrib",
  rsl: "rendermanrsl",
  risc: "riscript",
  riscript: "riscript",
  riscv: "risc-vassembly",
  riscvasm: "risc-vassembly",
  graph: "roboconf",
  instances: "roboconf",
  robot: "robotframework",
  rf: "robotframework",
  "rpm-specfile": "rpmspecfiles",
  rpm: "rpmspecfiles",
  spec: "rpmspecfiles",
  "rpm-spec": "rpmspecfiles",
  specfile: "rpmspecfiles",
  ruby: "ruby",
  rb: "ruby",
  gemspec: "ruby",
  podspec: "ruby",
  thor: "ruby",
  irb: "ruby",
  rust: "rust",
  rs: "rust",
  rvt: "rvtscript",
  "rvt-script": "rvtscript",
  SAS: "sas",
  sas: "sas",
  scss: "scss",
  sql: "sql",
  p23: "steppart21",
  step: "steppart21",
  stp: "steppart21",
  scala: "scala",
  scheme: "scheme",
  scilab: "scilab",
  sci: "scilab",
  sfz: "sfz",
  shexc: "shapeexpressions",
  shell: "shell",
  console: "shell",
  smali: "smali",
  smalltalk: "smalltalk",
  st: "smalltalk",
  sml: "sml",
  solidity: "solidity",
  sol: "solidity",
  spl: "splunkspl",
  stan: "stan",
  stanfuncs: "stan",
  stata: "stata",
  iecst: "structuredtext",
  scl: "structuredtext",
  stl: "structuredtext",
  "structured-text": "structuredtext",
  stylus: "stylus",
  styl: "stylus",
  subunit: "subunit",
  supercollider: "supercollider",
  sc: "supercollider",
  svelte: "svelte",
  swift: "swift",
  tcl: "tcl",
  tk: "tcl",
  terraform: "terraform(hcl)",
  tf: "terraform(hcl)",
  hcl: "terraform(hcl)",
  tap: "testanythingprotocol",
  thrift: "thrift",
  toit: "toit",
  tp: "tp",
  tsql: "transact-sql",
  twig: "twig",
  craftcms: "twig",
  typescript: "typescript",
  ts: "typescript",
  tsx: "react",
  mts: "typescript",
  cts: "typescript",
  "unicorn-rails-log": "unicornrailslog",
  vbnet: "vb.net",
  vb: "vb.net",
  vba: "vba",
  vbscript: "vbscript",
  vbs: "vbscript",
  vhdl: "vhdl",
  vala: "vala",
  verilog: "verilog",
  v: "verilog",
  vim: "vimscript",
  xsharp: "x#",
  xs: "x#",
  prg: "x#",
  axapta: "x++",
  "x++": "x++",
  x88asm: "x86assembly",
  x88asmatt: "x86assembly(at&t)",
  xl: "xl",
  tao: "xl",
  xquery: "xquery",
  xpath: "xquery",
  xq: "xquery",
  xqm: "xquery",
  yml: "yaml",
  yaml: "yaml",
  zenscript: "zenscript",
  zs: "zenscript",
  zephir: "zephir",
  zep: "zephir"
}

