export default {
  url: 'https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/',
  canonical: 'https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final',
  title: 'OpenSSL 3.0 Has Been Released! - OpenSSL Blog',
  image: '',
  favicons: [ { type: undefined, href: '/blog/favicon.png', sizes: undefined } ],
  author: 'OpenSSL Foundation, Inc.',
  description: 'After 3 years of development work, 17 alpha releases, 2 beta releases, over\n' +
    '7,500 commits and contributions from over 350 different authors we have …',
  keywords: '',
  source: '',
  price: '',
  priceCurrency: '',
  availability: '',
  robots: '',
  jsonld: {},
  'og:url': '',
  'og:locale': '',
  'og:locale:alternate': '',
  'og:title': '',
  'og:type': '',
  'og:description': '',
  'og:determiner': '',
  'og:site_name': '',
  'og:image': '',
  'og:image:secure_url': '',
  'og:image:type': '',
  'og:image:width': '',
  'og:image:height': '',
  'twitter:title': '',
  'twitter:description': '',
  'twitter:image': '',
  'twitter:image:alt': '',
  'twitter:card': '',
  'twitter:site': '',
  'twitter:site:id': '',
  'twitter:url': '',
  'twitter:account_id': '',
  'twitter:creator': '',
  'twitter:creator:id': '',
  'twitter:player': '',
  'twitter:player:width': '',
  'twitter:player:height': '',
  'twitter:player:stream': '',
  'twitter:app:name:iphone': '',
  'twitter:app:id:iphone': '',
  'twitter:app:url:iphone': '',
  'twitter:app:name:ipad': '',
  'twitter:app:id:ipad': '',
  'twitter:app:url:ipad': '',
  'twitter:app:name:googleplay': '',
  'twitter:app:id:googleplay': '',
  'twitter:app:url:googleplay': '',
  responseBody: '',
  HandheldFriendly: 'True',
  MobileOptimized: '320',
  viewport: 'width=device-width, initial-scale=1'
}
