import "./globals.css";
import "@code-hike/mdx/dist/index.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Navbar = () => {
  return (
    <header>
      <Link href={"/"}>
        <h1 className="px-24 pt-4 text-3xl">My Gorgeous Blog</h1>
      </Link>
    </header>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
